[package]
name = "howmanysmall/knit"
description = "Knit is a lightweight game framework"
version = "1.8.0"
license = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Comm = "sleitnick/comm@^1"
Promise = "evaera/promise@^4"
ThreadUtilities = "howmanysmall/thread-utilities@^1"
